[package]
description = "Ethcore IO library"
homepage = "https://github.com/dmdcoin/diamond-node"
license = "GPL-3.0"
name = "ethcore-io"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2024"

[dependencies]
fnv = "1.0"
mio = { version = "0.6.8", optional = true }
crossbeam-deque = "0.7.4"
parking_lot = "0.12"
log = "0.4"
slab = "0.4"
timer = "0.2"
time = "0.1"
tokio = "1.46"
futures = "0.1"
